server:
  port: 8020
#应用的名字
spring:
  application:
    name: OrderProviderApplication
dubbo:
  application:
    name: order-provider
  protocol:
    name: dubbo
    port: 20881
  registry:
    id: zk-registry
    address: zookeeper://127.0.0.1:2181?blockUntilConnectedWait=100000&timeout=100000 #需要加后边的串，不然容易报连接失败
  config-center:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181


management:
  metrics:
    export:
      prometheus:
        enabled: true
        step: 1m
        descriptions: true
    tags:
      application: ${spring.application.name}
  web:
    server:
      auto-time-requests: true
  endpoints:
    prometheus:
      id: springmetrics
    web:
      exposure:
        include: health,info,env,prometheus,metrics,httptrace,threaddump,heapdump,springmetrics

